version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: "partido"
    ports:
      - "5433:5432"
    volumes:
      - ~/volumes/partido/postgresql/:/var/lib/postgresql/data/